import type { MatchData } from "./types";

export const MATCHES: Record<string, MatchData> = {

  // ─── IRÃ vs NOVA ZELÂNDIA ─────────────────────────────────────────────────
  "iran-nz": {
    teamA: {
      name: "Irã", flag: "🇮🇷", coach: "Amir Ghalenoei",
      avgAttack: 2.2, avgDef: 1.1,
      matches: [
        { opp: "x Quirguistão", score: "3-2", type: "W", date: "Nov/24" },
        { opp: "x Coreia do Norte", score: "3-2", type: "W", date: "Nov/24" },
        { opp: "x UAE", score: "2-0", type: "W", date: "Mar/25" },
        { opp: "x Uzbequistão", score: "2-2", type: "D", date: "Mar/25" },
        { opp: "x Qatar", score: "0-1", type: "L", date: "Jun/25" },
        { opp: "x Coreia do Norte", score: "3-0", type: "W", date: "Jun/25" },
        { opp: "x Rússia", score: "1-2", type: "L", date: "Out/25" },
        { opp: "x Tanzânia", score: "2-0", type: "W", date: "Out/25" },
        { opp: "x Nigéria", score: "1-2", type: "L", date: "Mar/26" },
        { opp: "x Costa Rica", score: "5-0", type: "W", date: "Mar/26" },
      ],
      players: [
        { pos: "GK", name: "Alireza Beiranvand", club: "Tractor FC · 86 caps", rating: 7.1 },
        { pos: "RB", name: "Ramin Rezaeian", club: "Esteghlal", rating: 6.9 },
        { pos: "CB", name: "Shojae Khalilzadeh", club: "Tractor FC", rating: 7.0 },
        { pos: "CB", name: "H. Kanaanizadegan", club: "Zob Ahan", rating: 6.8 },
        { pos: "LB", name: "Ehsan Hajsafi", club: "Persepolis", rating: 7.0 },
        { pos: "DM", name: "Saeid Ezatolahi", club: "Anorthosis · 83 caps", rating: 7.3 },
        { pos: "DM", name: "Roozbeh Cheshmi", club: "Esteghlal", rating: 7.0 },
        { pos: "AM", name: "Mohammad Mohebi", club: "Al-Qadsiah · 14 gols", rating: 7.1 },
        { pos: "AM", name: "Saman Ghoddos", club: "Copenhagen", rating: 7.2 },
        { pos: "AM", name: "Mehdi Ghayedi", club: "Esteghlal · 10 gols", rating: 7.0 },
        { pos: "ST", name: "⭐ Mehdi Taremi", club: "Olympiacos · 56 gols/101 caps", rating: 7.8 },
      ],
      alerts: [
        { type: "amber", text: "⚠ Liga iraniana suspensa — jogadores sem ritmo competitivo" },
      ],
      setpieces: {
        goalsPct: 28, concededPct: 22, cornersFor: 5.1,
        foulsSuffered: 11.2, penalties: 1,
        note: "Taremi excelente cobrador de pênalti",
      },
      style: {
        formation: "4-2-3-1",
        description: "Bloco médio, sai rápido em transição. Aposta no individual de Taremi entre linhas.",
        possession: 48, passes: 380,
        pressing: 3, transition: 4, aerial: 3, creativity: 3, defensive: 4,
      },
      timing: {
        scored:   [2, 3, 4, 3, 4, 6, 0],
        conceded: [1, 1, 2, 2, 2, 3, 0],
        note: "8 dos 11 gols em Copas marcados no 2T — time de segundo tempo",
      },
    },
    teamB: {
      name: "Nova Zelândia", flag: "🇳🇿", coach: "Darren Bazeley",
      avgAttack: 0.7, avgDef: 1.8,
      matches: [
        { opp: "x México", score: "0-3", type: "L", date: "Set/24" },
        { opp: "x EUA", score: "1-1", type: "D", date: "Set/24" },
        { opp: "x Polônia", score: "0-1", type: "L", date: "Out/25" },
        { opp: "x Noruega", score: "1-1", type: "D", date: "Out/25" },
        { opp: "x Colômbia", score: "1-2", type: "L", date: "Nov/25" },
        { opp: "x Equador", score: "0-2", type: "L", date: "Nov/25" },
        { opp: "x Finlândia", score: "0-2", type: "L", date: "Nov/25" },
        { opp: "x Chile", score: "4-1", type: "W", date: "Mar/26" },
        { opp: "x Haiti", score: "0-4", type: "L", date: "Mar/26" },
        { opp: "x Inglaterra", score: "0-1", type: "L", date: "Jun/26" },
      ],
      players: [
        { pos: "GK", name: "Max Crocombe", club: "Millwall (ENG)", rating: 6.8 },
        { pos: "RB", name: "Tim Payne", club: "Wellington Phoenix", rating: 6.7 },
        { pos: "CB", name: "Michael Boxall", club: "Minnesota United (MLS)", rating: 6.8 },
        { pos: "CB", name: "Finn Surman", club: "Portland Timbers (MLS)", rating: 6.7 },
        { pos: "LB", name: "Liberato Cacace", club: "Wrexham AFC (ENG)", rating: 7.0 },
        { pos: "DM", name: "Joe Bell", club: "Viking FK (NOR)", rating: 6.9 },
        { pos: "DM", name: "Marko Stamenic", club: "Swansea City (ENG)", rating: 7.1 },
        { pos: "AM", name: "Matthew Garbett", club: "Peterborough Utd (ENG)", rating: 6.6 },
        { pos: "AM", name: "Sarpreet Singh", club: "Wellington Phoenix", rating: 6.9 },
        { pos: "AM", name: "Elijah Just", club: "Motherwell FC (SCO)", rating: 6.8 },
        { pos: "ST", name: "⭐ Chris Wood", club: "Nottm Forest · 45 gols/90 caps", rating: 7.5 },
      ],
      alerts: [
        { type: "red", text: "⚠ Ryan Thomas ausente (lesão)" },
        { type: "red", text: "⚠ Wood voltou de cirurgia no joelho em abril" },
      ],
      setpieces: {
        goalsPct: 41, concededPct: 18, cornersFor: 4.2,
        foulsSuffered: 9.8, penalties: 0,
        note: "Chris Wood — ameaça real em escanteios. 41% dos gols de bola parada",
      },
      style: {
        formation: "4-2-3-1",
        description: "Bloco baixo compacto. Busca bolas paradas e contra-ataque direto para Wood.",
        possession: 39, passes: 290,
        pressing: 2, transition: 3, aerial: 4, creativity: 2, defensive: 4,
      },
      timing: {
        scored:   [0, 1, 1, 1, 2, 2, 0],
        conceded: [2, 3, 2, 3, 2, 5, 1],
        note: "Defesa colapsa no 2T — 11 dos 18 gols sofridos após os 46 min",
      },
    },
    factors: [
      { label: "Qualidade ofensiva", scoreA: 4, scoreB: 2, winner: "A" },
      { label: "Solidez defensiva", scoreA: 4, scoreB: 3, winner: "A" },
      { label: "Exp. em Copas do Mundo", scoreA: 4, scoreB: 1, winner: "A" },
      { label: "Profundidade do elenco", scoreA: 3, scoreB: 2, winner: "A" },
      { label: "Ameaça de bola parada", scoreA: 3, scoreB: 4, winner: "B" },
      { label: "Ritmo competitivo", scoreA: 2, scoreB: 3, winner: "B" },
      { label: "Forma pré-torneio", scoreA: 4, scoreB: 2, winner: "A" },
    ],
    probA: 53.8, probD: 25.8, probB: 20.4,
    prediction: "Irã 1-0 Nova Zelândia",
    observation: "Irã vence num placar controlado. Taremi é o diferencial individual — Ezatolahi e Ghoddos sustentam o meio. Atenção ao impacto de bola parada da NZ no 2T, quando o bloco iraniano está menos concentrado e 41% dos gols neozelandeses vêm de situações paradas.",
    verdict: "Olhando todos os dados em conjunto, o Irã é superior em quase todos os vetores — médias de ataque (2.2 vs 0.7), qualidade individual com Taremi (7.8), e domínio nos fatores ABDE. Mas há dois números que me prendem atenção: a NZ tem 41% dos seus gols de bola parada, e o Irã marca historicamente no 2T (8 dos 11 gols em Copas após o intervalo). Isso cria um jogo onde o 1T provavelmente será 0-0 — os lambdas de Poisson (λA=1.65 / λB=0.45) apontam 1-0 como placar mais provável com ~17% de chance. Over 2.5 fica abaixo de 25%. A fragilidade real do Irã é a falta de ritmo competitivo — jogadores de Persepolis e Esteghlal sem jogar há meses. Isso é invisível no modelo mas aparece na tomada de decisão nos primeiros 20 minutos, exatamente quando a NZ é menos ameaçada. Se Wood ganhar um escanteio no 2T, o perigo é real. Minha leitura: Irã vence 1-0, controlando sem brilho. O único cenário de surpresa é um set piece da NZ no período em que o Irã ainda está 'frio'.",
    tags: [
      { text: "Irã favorito", color: "blue" },
      { text: "Under 2.5 gols", color: "green" },
      { text: "Wood — perigo em set pieces", color: "amber" },
      { text: "NZ — 0 clean sheets nos últimos 10", color: "red" },
    ],
    group: "Grupo G", date: "16 Jun · 21h00 ET", venue: "Los Angeles Stadium",
  },

  // ─── FRANÇA vs SENEGAL ────────────────────────────────────────────────────
  "fra-sen": {
    teamA: {
      name: "França", flag: "🇫🇷", coach: "Didier Deschamps (14 anos)",
      avgAttack: 2.6, avgDef: 1.0,
      matches: [
        { opp: "x Azerbaijão", score: "3-0", type: "W", date: "Out/25" },
        { opp: "x Islândia", score: "2-2", type: "D", date: "Out/25" },
        { opp: "x Ucrânia", score: "4-0", type: "W", date: "Nov/25" },
        { opp: "x Azerbaijão", score: "3-1", type: "W", date: "Nov/25" },
        { opp: "x Brasil", score: "2-1", type: "W", date: "Mar/26" },
        { opp: "x Colômbia", score: "3-1", type: "W", date: "Mar/26" },
        { opp: "x Costa do Marfim", score: "1-2", type: "L", date: "Jun/26" },
        { opp: "x Irlanda do Norte", score: "3-1", type: "W", date: "Jun/26" },
      ],
      players: [
        { pos: "GK", name: "Mike Maignan", club: "AC Milan", rating: 7.3 },
        { pos: "RB", name: "Jules Koundé", club: "FC Barcelona", rating: 7.5 },
        { pos: "CB", name: "William Saliba", club: "Arsenal", rating: 7.6 },
        { pos: "CB", name: "Dayot Upamecano", club: "Bayern Munich", rating: 7.2 },
        { pos: "LB", name: "Théo Hernandez", club: "Al-Hilal", rating: 7.5 },
        { pos: "DM", name: "Aurélien Tchouaméni", club: "Real Madrid", rating: 7.4 },
        { pos: "DM", name: "Adrien Rabiot", club: "Marseille", rating: 7.1 },
        { pos: "AM", name: "Michael Olise", club: "Bayern Munich · 3G em 2026", rating: 7.6 },
        { pos: "AM", name: "⭐ Ousmane Dembélé", club: "PSG · Bola de Ouro 2025", rating: 7.8 },
        { pos: "AM", name: "Désiré Doué", club: "PSG · hat-trick vs NIR", rating: 7.7 },
        { pos: "ST", name: "⭐ Kylian Mbappé", club: "Real Madrid · 56G · 1 do record", rating: 8.2 },
      ],
      alerts: [
        { type: "amber", text: "⚠ Saliba com dores nas costas — monitorado, deve jogar" },
      ],
      setpieces: {
        goalsPct: 24, concededPct: 19, cornersFor: 6.8,
        foulsSuffered: 12.1, penalties: 2,
        note: "Mbappé e Dembélé letais em faltas diretas",
      },
      style: {
        formation: "4-2-3-1",
        description: "Alta posse, pressão intensa, transições rápidas pelos flancos. Mbappé explora profundidade constante.",
        possession: 62, passes: 530,
        pressing: 5, transition: 5, aerial: 3, creativity: 5, defensive: 4,
      },
      timing: {
        scored:   [3, 4, 5, 4, 5, 3, 2],
        conceded: [1, 2, 1, 2, 1, 1, 0],
        note: "Gols distribuídos uniformemente — não tem período de baixa",
      },
    },
    teamB: {
      name: "Senegal", flag: "🇸🇳", coach: "Pape Bouna Thiaw",
      avgAttack: 1.8, avgDef: 0.8,
      matches: [
        { opp: "x Botsuana", score: "3-0", type: "W", date: "Dez/25" },
        { opp: "x Benin (AFCON)", score: "3-0", type: "W", date: "Dez/25" },
        { opp: "x Sudão (AFCON)", score: "3-1", type: "W", date: "Jan/26" },
        { opp: "x Mali (AFCON)", score: "1-0", type: "W", date: "Jan/26" },
        { opp: "x Egito (AFCON)", score: "1-0", type: "W", date: "Jan/26" },
        { opp: "x Marrocos (Final)", score: "0-3", type: "L", date: "Jan/26" },
        { opp: "x Peru", score: "2-0", type: "W", date: "Mar/26" },
        { opp: "x Gâmbia", score: "3-1", type: "W", date: "Mar/26" },
        { opp: "x EUA", score: "2-3", type: "L", date: "Mai/26" },
        { opp: "x Arábia Saudita", score: "0-0", type: "D", date: "Jun/26" },
      ],
      players: [
        { pos: "GK", name: "Edouard Mendy", club: "Al Ahli · 34 anos", rating: 7.1 },
        { pos: "RB", name: "Formose Mendy / Diatta", club: "Bordeaux / Monaco", rating: 6.9 },
        { pos: "CB", name: "⚠ Kalidou Koulibaly (c)", club: "Al-Hilal · lesão quadríceps", rating: 7.2 },
        { pos: "CB", name: "Niakhate / Diallo", club: "Nottm Forest / Man Utd", rating: 7.0 },
        { pos: "LB", name: "Fode Ballo-Touré", club: "Fulham", rating: 6.8 },
        { pos: "CM", name: "Lamine Camara", club: "Monaco · jovem destaque", rating: 7.2 },
        { pos: "CM", name: "Pape Matar Sarr", club: "Tottenham · top scorer qualif.", rating: 7.4 },
        { pos: "CM", name: "Pape Gueye", club: "Marseille", rating: 7.0 },
        { pos: "LW", name: "Ismaila Sarr", club: "Crystal Palace", rating: 7.1 },
        { pos: "ST", name: "Nicolas Jackson", club: "Bayern Munich", rating: 7.2 },
        { pos: "RW", name: "⭐ Sadio Mané", club: "Al Nassr · 2G vs EUA · 34 anos", rating: 7.6 },
      ],
      alerts: [
        { type: "red", text: "⚠ Koulibaly — lesão quadríceps, jogou só 8min no último amistoso" },
        { type: "amber", text: "⚠ Thiaw é treinador novo no cargo" },
      ],
      setpieces: {
        goalsPct: 33, concededPct: 27, cornersFor: 4.5,
        foulsSuffered: 10.3, penalties: 1,
        note: "Koulibaly ausente mina a cobertura aérea defensiva",
      },
      style: {
        formation: "4-3-3",
        description: "Bloco médio-baixo, busca transições via Mané e Sarr pelos flancos. Físico e direto.",
        possession: 47, passes: 380,
        pressing: 3, transition: 4, aerial: 4, creativity: 3, defensive: 3,
      },
      timing: {
        scored:   [1, 2, 3, 2, 3, 4, 1],
        conceded: [1, 1, 1, 2, 2, 1, 0],
        note: "Forte no início, produção cresce no 2T mas começa a ceder fisicamente",
      },
    },
    factors: [
      { label: "Poder ofensivo", scoreA: 5, scoreB: 3, winner: "A" },
      { label: "Solidez defensiva", scoreA: 4, scoreB: 3, winner: "A" },
      { label: "Profundidade do elenco", scoreA: 5, scoreB: 3, winner: "A" },
      { label: "Velocidade / transição", scoreA: 4, scoreB: 4, winner: "tie" },
      { label: "Fisicalidade e duelos", scoreA: 3, scoreB: 4, winner: "B" },
      { label: "Capacidade de upset", scoreA: 1, scoreB: 4, winner: "B" },
      { label: "Saúde do plantel", scoreA: 4, scoreB: 2, winner: "A" },
      { label: "Exp. em Copas do Mundo", scoreA: 5, scoreB: 3, winner: "A" },
    ],
    probA: 60, probD: 22, probB: 15,
    prediction: "França 2-0 Senegal",
    observation: "A qualidade individual da França é incompatível com qualquer cenário de derrota aqui. O único perigo real é Mané nas costas de Théo Hernandez em transição. Com Koulibaly a 8 minutos de ritmo e 27% dos gols senegaleses sofridos de bola parada, a linha defensiva está exposta exatamente onde a França mais ataca.",
    verdict: "Cruzando todos os dados, a França domina em praticamente todas as dimensões: média de ataque 2.6 vs 1.8, 62% de posse, pressing máximo (5/5), ataque mais variado do torneio com Mbappé (8.2), Dembélé (7.8) e Doué (7.7). O lambda de Poisson resulta em λA=1.7 vs λB=0.9 — placar mais provável 1-0 com ~16% e 2-0 logo atrás com ~14%, Over 2.5 em ~52%. O ponto crítico é o Senegal com Koulibaly em apenas 8 minutos no último amistoso: com 27% dos gols sofridos de bola parada e sem o líder defensivo em ritmo, a França tem 6.8 escanteios por jogo e Mbappé/Dembélé em faltas. O timing mostra que a França marca em todos os intervalos sem cair de rendimento — o Senegal não consegue 'segurar' por 90 minutos. O único cenário de surpresa realista é Mané receber um lançamento nas costas de Théo Hernandez (que sobe demais) e marcar no 1T, mudando a dinâmica emocional. Mas olhando a matriz completa: probabilidade de vitória francesa ~60%, empate ~22%. Não há base nos dados para apostar contra a França aqui.",
    tags: [
      { text: "França massiva favorita", color: "blue" },
      { text: "Over 2.5 gols plausível", color: "green" },
      { text: "Koulibaly — fitness duvidoso", color: "amber" },
      { text: "Mbappé — 1G do record histórico", color: "red" },
      { text: "Mané — principal ameaça SEN", color: "purple" },
    ],
    group: "Grupo I", date: "16 Jun · 15h00 ET", venue: "MetLife Stadium · NJ",
  },

  // ─── BRASIL vs MARROCOS ───────────────────────────────────────────────────
  "bra-mar": {
    teamA: {
      name: "Brasil", flag: "🇧🇷", coach: "Carlo Ancelotti (desde mai/25)",
      avgAttack: 2.5, avgDef: 1.1,
      matches: [
        { opp: "x Chile", score: "3-0", type: "W", date: "Set/25" },
        { opp: "x Bolívia", score: "0-1", type: "L", date: "Set/25" },
        { opp: "x Coreia do Sul", score: "5-0", type: "W", date: "Out/25" },
        { opp: "x Japão", score: "2-3", type: "L", date: "Out/25" },
        { opp: "x Senegal", score: "2-0", type: "W", date: "Nov/25" },
        { opp: "x Tunísia", score: "1-1", type: "D", date: "Nov/25" },
        { opp: "x França", score: "1-2", type: "L", date: "Mar/26" },
        { opp: "x Croácia", score: "3-1", type: "W", date: "Abr/26" },
        { opp: "x Panamá", score: "6-2", type: "W", date: "Mai/26" },
        { opp: "x Egito", score: "2-1", type: "W", date: "Jun/26" },
      ],
      players: [
        { pos: "GK", name: "Alisson Becker", club: "Liverpool", rating: 7.5 },
        { pos: "RB", name: "Danilo", club: "Flamengo — Wesley lesionado (Copa out)", rating: 6.9 },
        { pos: "CB", name: "Marquinhos (c)", club: "PSG", rating: 7.4 },
        { pos: "CB", name: "Gabriel Magalhães", club: "Arsenal", rating: 7.5 },
        { pos: "LB", name: "Alex Sandro", club: "Flamengo", rating: 7.0 },
        { pos: "DM", name: "Casemiro", club: "Manchester United", rating: 7.1 },
        { pos: "DM", name: "Bruno Guimarães", club: "Newcastle", rating: 7.6 },
        { pos: "AM", name: "⭐ Raphinha", club: "Barcelona · top scorer qualif. (5G)", rating: 7.8 },
        { pos: "AM", name: "Lucas Paquetá", club: "West Ham", rating: 7.2 },
        { pos: "AM", name: "⭐ Vinícius Jr.", club: "Real Madrid", rating: 8.0 },
        { pos: "ST", name: "Igor Thiago / Cunha", club: "Brentford / Wolves", rating: 6.7 },
      ],
      alerts: [
        { type: "red", text: "⚠ Neymar duvidoso — panturrilha grau 2" },
        { type: "red", text: "⚠ Wesley fora da Copa inteira — dilema no RB" },
      ],
      setpieces: {
        goalsPct: 31, concededPct: 24, cornersFor: 6.2,
        foulsSuffered: 11.8, penalties: 2,
        note: "Gabriel Magalhães — cabeceador de elite em escanteios ofensivos",
      },
      style: {
        formation: "4-2-3-1",
        description: "Jogo ofensivo pelos flancos com Vini e Raphinha. Ancelotti libera criatividade individual.",
        possession: 58, passes: 480,
        pressing: 4, transition: 5, aerial: 3, creativity: 5, defensive: 3,
      },
      timing: {
        scored:   [3, 4, 3, 4, 5, 5, 1],
        conceded: [1, 2, 2, 2, 1, 3, 0],
        note: "Produtivo ao longo de todo o jogo — sem período de apagão",
      },
    },
    teamB: {
      name: "Marrocos", flag: "🇲🇦", coach: "Mohamed Ouahbi (novo)",
      avgAttack: 1.5, avgDef: 0.2,
      matches: [
        { opp: "x Tanzânia (Q.)", score: "1-0", type: "W", date: "Out/25" },
        { opp: "x Amistoso", score: "4-0", type: "W", date: "Nov/25" },
        { opp: "x Amistoso", score: "1-0", type: "W", date: "Nov/25" },
        { opp: "x Zâmbia (AFCON)", score: "3-0", type: "W", date: "Dez/25" },
        { opp: "x RD Congo (AFCON)", score: "1-0", type: "W", date: "Jan/26" },
        { opp: "x Camarões (AFCON)", score: "2-0", type: "W", date: "Jan/26" },
        { opp: "x Nigéria (AFCON SF)", score: "0-0 (4-2 pên)", type: "W", date: "Jan/26" },
        { opp: "x Senegal (Final AFCON)", score: "3-0", type: "W", date: "Jan/26" },
        { opp: "x Noruega", score: "1-1", type: "D", date: "Jun/26" },
      ],
      players: [
        { pos: "GK", name: "Yassine Bounou (Bono)", club: "Al-Hilal · reflexos de elite", rating: 7.4 },
        { pos: "RB", name: "⭐ Achraf Hakimi (c)", club: "PSG · melhor lateral do mundo", rating: 7.9 },
        { pos: "CB", name: "Issa Diop / Chadi Riad", club: "Fulham / Celtic — Aguerd fora", rating: 6.9 },
        { pos: "CB", name: "Jawad El Yamiq", club: "Al-Najma", rating: 7.0 },
        { pos: "LB", name: "Noussair Mazraoui", club: "Man Utd — ombro duvidoso", rating: 7.1 },
        { pos: "DM", name: "Sofyan Amrabat", club: "Real Betis · âncora defensiva", rating: 7.4 },
        { pos: "DM", name: "Nabil El Aynaoui", club: "AS Roma", rating: 7.1 },
        { pos: "AM", name: "⭐ Bilal El Khannouss", club: "VfB Stuttgart", rating: 7.7 },
        { pos: "AM", name: "Azzedine Ounahi", club: "Girona", rating: 7.2 },
        { pos: "AM", name: "⭐ Brahim Díaz", club: "Real Madrid · 5G na AFCON", rating: 7.8 },
        { pos: "ST", name: "Ismael Saibari / El Kaabi", club: "PSV / Olympiakos", rating: 7.3 },
      ],
      alerts: [
        { type: "red", text: "⚠ Aguerd fora da Copa — CB mais experiente ausente" },
        { type: "red", text: "⚠ Ezzalzouli fora da Copa — lesão" },
        { type: "amber", text: "⚠ Mazraoui — ombro duvidoso · Ouahbi novo no cargo" },
      ],
      setpieces: {
        goalsPct: 38, concededPct: 15, cornersFor: 4.8,
        foulsSuffered: 9.6, penalties: 0,
        note: "6 clean sheets na qualificação — defesa sólida até em bola parada",
      },
      style: {
        formation: "4-2-3-1 / 4-4-2",
        description: "Bloco organizado, contra-ataque veloz. Hakimi e Brahim Díaz exploram o lado direito.",
        possession: 44, passes: 360,
        pressing: 3, transition: 4, aerial: 3, creativity: 4, defensive: 5,
      },
      timing: {
        scored:   [1, 2, 2, 2, 2, 3, 1],
        conceded: [0, 0, 0, 1, 0, 1, 0],
        note: "Defesa impenetrável — só 2 gols sofridos nos últimos 9 jogos",
      },
    },
    factors: [
      { label: "Poder ofensivo", scoreA: 4, scoreB: 3, winner: "A" },
      { label: "Solidez defensiva", scoreA: 4, scoreB: 5, winner: "B" },
      { label: "Forma recente", scoreA: 3, scoreB: 4, winner: "B" },
      { label: "Qualidade individual", scoreA: 5, scoreB: 4, winner: "A" },
      { label: "Impacto de lesões", scoreA: 2, scoreB: 2, winner: "tie" },
      { label: "Exp. em Copas do Mundo", scoreA: 5, scoreB: 4, winner: "A" },
      { label: "Treinador / sistema", scoreA: 4, scoreB: 2, winner: "A" },
    ],
    probA: 50, probD: 28, probB: 22,
    prediction: "Brasil 2-1 Marrocos",
    observation: "Jogo de sistemas. Ancelotti vs bloco marroquino. Se o Brasil marcar primeiro Marrocos vai abrir espaços e o 2-0 é inevitável. Se ficar 0-0 até o intervalo, o peso psicológico cresce. Marrocos só sofreu 2 gols nos últimos 9 jogos — esse número precisa ser levado a sério.",
    verdict: "Este é o jogo mais difícil de analisar. Os lambdas de Poisson ficam em λA≈1.35 e λB≈0.8 — o resultado mais provável pela matriz é 1-0 Brasil (~15%), seguido de 0-0 (~14%) e 1-1 (~13%). Isso confirma o que os dados gritam: Marrocos com 0.2 gols sofridos por jogo e timing quase zerado nos conceded é uma barreira diferente de qualquer adversário que o Brasil vai enfrentar. O Brasil ataca pelos flancos (Vini+Raphinha) mas Amrabat cobre exatamente esse espaço. Sem Neymar segurando a bola entre linhas, o ST (6.7 de rating) não retém bola, o que isola os extremos. O Marrocos por sua vez marca 38% dos gols de bola parada — e Gabriel Magalhães, o melhor cabeceador do Brasil, joga pelo lado errado para cobrir nisso. Probabilidade de empate (28%) é maior do que a vitória do Marrocos (22%), o que sugere um jogo truncado onde quem marcar primeiro dita o resultado. Minha leitura cruzando todos os vetores: o Poisson favorece o Brasil, mas os dados qualitativos apontam para um empate como resultado mais justo.",
    tags: [
      { text: "Brasil favorito moderado", color: "blue" },
      { text: "Over 2.5 possível", color: "green" },
      { text: "Neymar ausente — ST fraco", color: "amber" },
      { text: "Marrocos — melhor defesa AFCON", color: "purple" },
      { text: "Aguerd fora — CB exp. ausente", color: "red" },
    ],
    group: "Grupo C", date: "13 Jun · 18h00 ET", venue: "MetLife Stadium · NJ",
    note: "⚠ Análise pré-jogo reconstituída — resultado real 1×1 ignorado conforme solicitado",
  },

  // ─── ARÁBIA SAUDITA vs URUGUAI ────────────────────────────────────────────
  "sau-uru": {
    teamA: {
      name: "Arábia Saudita", flag: "🇸🇦", coach: "Georgios Donis (desde abr/26)",
      avgAttack: 1.1, avgDef: 1.4,
      matches: [
        { opp: "x Tchéquia", score: "1-1", type: "D", date: "Out/25" },
        { opp: "x Indonésia (Q.)", score: "3-2", type: "W", date: "Out/25" },
        { opp: "x Iraque (Q.)", score: "0-0", type: "D", date: "Nov/25" },
        { opp: "x Costa do Marfim", score: "1-0", type: "W", date: "Nov/25" },
        { opp: "x Argélia", score: "0-2", type: "L", date: "Dez/25" },
        { opp: "x Comores (Copa Árabe)", score: "3-1", type: "W", date: "Dez/25" },
        { opp: "x Marrocos (Copa Árabe)", score: "0-1", type: "L", date: "Dez/25" },
        { opp: "x Egito", score: "0-4", type: "L", date: "Mar/26" },
        { opp: "x Sérvia", score: "1-2", type: "L", date: "Mai/26" },
        { opp: "x Senegal", score: "0-0", type: "D", date: "Jun/26" },
      ],
      players: [
        { pos: "GK", name: "Mohammed Al-Owais", club: "Al-Hilal · 1º goleiro titular", rating: 7.0 },
        { pos: "RB", name: "Sultan Al-Ghanam", club: "Al-Hilal", rating: 6.8 },
        { pos: "CB", name: "Ali Al-Bulaihi", club: "Al-Hilal · veterano 35 anos", rating: 6.9 },
        { pos: "CB", name: "Hassan Tambakti", club: "Al-Qadsiah", rating: 6.8 },
        { pos: "LB", name: "Yasser Al-Shahrani", club: "Al-Hilal", rating: 6.9 },
        { pos: "DM", name: "Mohammed Kanno", club: "Al-Hilal · capitão", rating: 7.1 },
        { pos: "DM", name: "Ali Al-Hassan", club: "Al-Ittihad", rating: 6.9 },
        { pos: "AM", name: "Sami Al-Najei", club: "Al-Qadsiah", rating: 6.8 },
        { pos: "AM", name: "⭐ Salem Al-Dawsari", club: "Al-Hilal · herói vs Argentina 2022", rating: 7.4 },
        { pos: "AM", name: "Riyadh Sharahili", club: "Al-Hilal", rating: 6.7 },
        { pos: "ST", name: "⭐ Firas Al-Buraikan", club: "Al-Fateh · top scorer seleção ativa", rating: 7.2 },
      ],
      alerts: [
        { type: "amber", text: "⚠ Donis assumiu apenas em abril/26 — 3 meses de trabalho" },
        { type: "red", text: "⚠ 0-4 vs Egito e 1-2 vs Sérvia — forma defensiva preocupante" },
      ],
      setpieces: {
        goalsPct: 35, concededPct: 30, cornersFor: 4.2,
        foulsSuffered: 10.8, penalties: 1,
        note: "Al-Dawsari perigoso em cobranças diretas de falta",
      },
      style: {
        formation: "4-2-3-1 / 4-4-2",
        description: "Bloco médio, jogo físico e direto. Depende de Al-Dawsari para criar. Sistema ainda indefinido com Donis.",
        possession: 43, passes: 330,
        pressing: 2, transition: 3, aerial: 4, creativity: 2, defensive: 3,
      },
      timing: {
        scored:   [1, 2, 1, 2, 2, 2, 1],
        conceded: [2, 3, 2, 2, 2, 2, 1],
        note: "Vulnerável no início — 5 dos 14 gols sofridos nos primeiros 30 min",
      },
    },
    teamB: {
      name: "Uruguai", flag: "🇺🇾", coach: "Marcelo Bielsa (desde 2023)",
      avgAttack: 1.2, avgDef: 1.3,
      matches: [
        { opp: "x Paraguai (Q.)", score: "0-2", type: "L", date: "Jun/25" },
        { opp: "x Venezuela (Q.)", score: "2-0", type: "W", date: "Jun/25" },
        { opp: "x Peru", score: "3-0", type: "W", date: "Set/25" },
        { opp: "x Chile (Q.)", score: "0-0", type: "D", date: "Set/25" },
        { opp: "x Rep. Dominicana", score: "1-0", type: "W", date: "Out/25" },
        { opp: "x Uzbequistão", score: "2-1", type: "W", date: "Out/25" },
        { opp: "x México", score: "0-0", type: "D", date: "Nov/25" },
        { opp: "x EUA", score: "1-5", type: "L", date: "Nov/25" },
        { opp: "x Bolívia", score: "0-0", type: "D", date: "Mar/26" },
        { opp: "x Inglaterra", score: "0-3", type: "L", date: "Mar/26" },
      ],
      players: [
        { pos: "GK", name: "Fernando Muslera", club: "Galatasaray · veterano 38 anos", rating: 7.0 },
        { pos: "RB", name: "Guillermo Varela", club: "Flamengo", rating: 6.9 },
        { pos: "CB", name: "⭐ Ronald Araújo (c)", club: "Barcelona · capitão", rating: 7.8 },
        { pos: "CB", name: "⭐ José María Giménez", club: "Atlético de Madrid", rating: 7.6 },
        { pos: "LB", name: "Mathías Olivera", club: "Napoli", rating: 7.1 },
        { pos: "DM", name: "⭐ Manuel Ugarte", club: "Manchester United", rating: 7.5 },
        { pos: "CM", name: "⭐ Federico Valverde", club: "Real Madrid · motor e líder técnico", rating: 8.0 },
        { pos: "AM", name: "Rodrigo Bentancur", club: "Tottenham", rating: 7.2 },
        { pos: "AM", name: "Nicolás de la Cruz", club: "Flamengo", rating: 7.1 },
        { pos: "AM", name: "Facundo Pellistri", club: "Panathinaikos", rating: 6.9 },
        { pos: "ST", name: "⭐ Darwin Núñez", club: "Al-Hilal · 13 gols/36 caps", rating: 7.6 },
      ],
      alerts: [
        { type: "red", text: "⚠ De Arrascaeta duvidoso — panturrilha, pode desfalcar" },
        { type: "amber", text: "⚠ Suárez e Cavani aposentados — Darwin carrega o ataque sozinho" },
      ],
      setpieces: {
        goalsPct: 22, concededPct: 18, cornersFor: 5.6,
        foulsSuffered: 11.4, penalties: 1,
        note: "Araújo e Giménez dominam o aéreo defensivo — difíceis de bater em bola parada",
      },
      style: {
        formation: "4-2-3-1",
        description: "Alta pressão estilo Bielsa, saída de bola rápida, Valverde como pivô ofensivo. Profundidade via Núñez.",
        possession: 52, passes: 430,
        pressing: 5, transition: 4, aerial: 4, creativity: 3, defensive: 4,
      },
      timing: {
        scored:   [1, 2, 2, 2, 2, 2, 1],
        conceded: [2, 2, 2, 2, 2, 3, 0],
        note: "Produção ofensiva baixa e irregular — 12 gols nos últimos 10 jogos",
      },
    },
    factors: [
      { label: "Qualidade ofensiva", scoreA: 2, scoreB: 3, winner: "B" },
      { label: "Solidez defensiva", scoreA: 2, scoreB: 4, winner: "B" },
      { label: "Qualidade individual", scoreA: 2, scoreB: 5, winner: "B" },
      { label: "Estilo / sistema tático", scoreA: 2, scoreB: 4, winner: "B" },
      { label: "Exp. em Copas do Mundo", scoreA: 3, scoreB: 4, winner: "B" },
      { label: "Forma recente", scoreA: 2, scoreB: 2, winner: "tie" },
      { label: "Fator surpresa / upset", scoreA: 4, scoreB: 1, winner: "A" },
      { label: "Ritmo competitivo", scoreA: 3, scoreB: 3, winner: "tie" },
    ],
    probA: 18, probD: 30, probB: 52,
    prediction: "Uruguai 1-0 Arábia Saudita",
    observation: "Valverde e Araújo são a diferença de classe. Com pressing de Bielsa desde o apito inicial, a Arábia Saudita vai sofrer para sair. Darwin Núñez precisa de uma chance para decidir. A maior ameaça saudita é Al-Dawsari em cobranças de falta — Araújo e Giménez no aéreo devem anular o restante.",
    verdict: "Os lambdas de Poisson ficam em λA≈0.7 e λB≈1.25 — e já aqui está a história do jogo: o Uruguai vai criar mais, mas vai converter pouco. O placar mais provável pela matriz é 1-0 Uruguai (~17%), seguido de 0-0 (~20%) e 1-1 (~12%). O empate em 30% de probabilidade é o número que mais chama atenção — acima da vitória saudita (18%), o que indica um jogo truncado. A Arábia Saudita é vulnerável nos primeiros 30 minutos (5 dos 14 gols sofridos nesse período) e o pressing de Bielsa começa máximo — se Valverde ou Núñez marcarem cedo, o jogo está resolvido. O problema do Uruguai: 1.2 gols por jogo com 4 empates nos últimos 10, e sem De Arrascaeta para criar entre linhas. A Arábia Saudita tem 35% dos gols de bola parada e Al-Dawsari em faltas diretas — se o Uruguai fizer faltas desnecessárias no setor médio, há risco real. Mas Araújo (7.8) e Giménez (7.6) no aéreo defensivo anulam esse perigo. Olhando todos os vetores: Uruguai deve vencer, mas pode não ser fácil. O modelo aponta para um jogo de poucos gols — Under 2.5 é quase certo.",
    tags: [
      { text: "Uruguai favorito claro", color: "purple" },
      { text: "Under 2.5 gols provável", color: "green" },
      { text: "Valverde — melhor em campo", color: "purple" },
      { text: "Al-Dawsari — única ameaça SAU", color: "amber" },
      { text: "De Arrascaeta duvidoso", color: "red" },
      { text: "KSA — Donis só 3 meses no cargo", color: "red" },
    ],
    group: "Grupo H", date: "15 Jun · 18h00 ET", venue: "Hard Rock Stadium · Miami",
  },

  "bel-egy": {
    teamA: {
      name: "Bélgica", flag: "🇧🇪", coach: "Rudi Garcia (desde jan/25)",
      avgAttack: 2.3, avgDef: 0.9,
      matches: [
        { opp: "x Kazakhstan",       score: "6-0", type: "W", date: "Set/25" },
        { opp: "x Macedonia do N.",   score: "0-0", type: "D", date: "Out/25" },
        { opp: "x Wales",             score: "4-2", type: "W", date: "Out/25" },
        { opp: "x Kazakhstan",        score: "1-1", type: "D", date: "Nov/25" },
        { opp: "x Liechtenstein",     score: "7-0", type: "W", date: "Nov/25" },
        { opp: "x EUA",               score: "5-2", type: "W", date: "Mar/26" },
        { opp: "x México",            score: "1-1", type: "D", date: "Abr/26" },
        { opp: "x Croácia",           score: "2-1", type: "W", date: "Jun/26" },
        { opp: "x Tunísia",           score: "5-0", type: "W", date: "Jun/26" },
        { opp: "x Wales",             score: "4-2", type: "W", date: "Jun/26" },
      ],
      players: [
        { pos: "GK", name: "Thibaut Courtois",     club: "Real Madrid · reflexos de elite",            rating: 7.5 },
        { pos: "RB", name: "Timothy Castagne",      club: "Fulham",                                     rating: 7.0 },
        { pos: "CB", name: "Arthur Theate",         club: "Eintracht Frankfurt",                        rating: 7.1 },
        { pos: "CB", name: "Zeno Debast",           club: "Sporting CP — dúvida (substituível por Mechele)", rating: 7.0 },
        { pos: "LB", name: "Maxim De Cuyper",       club: "Brighton",                                   rating: 7.0 },
        { pos: "DM", name: "⭐ Amadou Onana",       club: "Aston Villa · motor defensivo",              rating: 7.6 },
        { pos: "DM", name: "Youri Tielemans (c)",   club: "Aston Villa · Europa League 25/26",         rating: 7.4 },
        { pos: "AM", name: "Jérémy Doku",           club: "Manchester City · explosão pelo flanco",     rating: 7.5 },
        { pos: "AM", name: "⭐ Kevin De Bruyne",    club: "Napoli · 37G/119caps · último Mundial",      rating: 8.0 },
        { pos: "AM", name: "Leandro Trossard",      club: "Arsenal",                                    rating: 7.3 },
        { pos: "ST", name: "⭐ Romelu Lukaku",      club: "Napoli · 90 gols/126 caps · recordista",    rating: 7.2 },
      ],
      alerts: [
        { type: "amber", text: "⚠ Lukaku — temporada na Napoli comprometida por lesões; ritmo de jogo abaixo do ideal" },
        { type: "amber", text: "⚠ Debast — dúvida na zaga; Mechele ou Ngoy como sombra" },
        { type: "amber", text: "⚠ Defesa vulnerável — concedeu 5 gols em 2 jogos vs Wales na qualificação" },
      ],
      setpieces: {
        goalsPct: 29, concededPct: 25, cornersFor: 6.4,
        foulsSuffered: 11.6, penalties: 2,
        note: "De Bruyne e Tielemans cobradores de alto nível. Lukaku — ameaça aérea real em escanteios",
      },
      style: {
        formation: "4-2-3-1",
        description: "Posse alta, pressing intenso, transições velozes pelos flancos. De Bruyne como #10 livre entre linhas. Doku explode pela direita com velocidade.",
        possession: 64, passes: 540,
        pressing: 4, transition: 4, aerial: 3, creativity: 5, defensive: 3,
      },
      timing: {
        scored:   [4, 5, 6, 5, 7, 8, 2],
        conceded: [1, 2, 2, 2, 1, 2, 0],
        note: "Cresce no 2T — pico entre 76–90min. Sem período de apagão em nenhum intervalo",
      },
    },
    teamB: {
      name: "Egito", flag: "🇪🇬", coach: "Hossam Hassan",
      avgAttack: 1.5, avgDef: 0.5,
      matches: [
        { opp: "x Angola (AFCON)",      score: "0-0", type: "D", date: "Dez/25" },
        { opp: "x Zimbabwe (AFCON)",    score: "2-1", type: "W", date: "Dez/25" },
        { opp: "x África do Sul",       score: "1-0", type: "W", date: "Dez/25" },
        { opp: "x Benin (AFCON)",       score: "3-1", type: "W", date: "Jan/26" },
        { opp: "x Costa do Marfim",     score: "3-2", type: "W", date: "Jan/26" },
        { opp: "x Senegal (AFCON SF)",  score: "0-1", type: "L", date: "Jan/26" },
        { opp: "x Nigéria (AFCON)",     score: "0-0", type: "D", date: "Jan/26" },
        { opp: "x Arábia Saudita",      score: "4-0", type: "W", date: "Mar/26" },
        { opp: "x Espanha",             score: "0-0", type: "D", date: "Mar/26" },
        { opp: "x Brasil",              score: "1-2", type: "L", date: "Jun/26" },
      ],
      players: [
        { pos: "GK", name: "Mostafa Shobeir",       club: "Al Ahly",                                          rating: 6.9 },
        { pos: "RB", name: "Mohamed Hany",          club: "Al Ahly",                                          rating: 6.7 },
        { pos: "CB", name: "Mohamed Abdelmonem",    club: "OGC Nice · compostura e aéreo",                   rating: 7.1 },
        { pos: "CB", name: "Yasser Ibrahim",        club: "Al Ahly",                                          rating: 6.8 },
        { pos: "LB", name: "Ahmed Fatouh",          club: "Pyramids FC",                                      rating: 6.7 },
        { pos: "DM", name: "Marwan Attia",          club: "Al Ahly",                                          rating: 6.8 },
        { pos: "DM", name: "Emam Ashour",           club: "Zamalek",                                          rating: 6.9 },
        { pos: "AM", name: "Mostafa Ziko",          club: "Al Ahly",                                          rating: 6.7 },
        { pos: "AM", name: "⭐ Mohamed Salah (c)",  club: "Liverpool · 67 gols/115 caps · 2G do recorde",    rating: 8.1 },
        { pos: "AM", name: "Trezeguet",             club: "Al Ahly",                                          rating: 6.8 },
        { pos: "ST", name: "⭐ Omar Marmoush",      club: "Manchester City · breakthrough 25/26",             rating: 7.5 },
      ],
      alerts: [
        { type: "amber", text: "⚠ Salah — recuperou de lesão na coxa (abr/26); saiu no 2T vs Brasil; ritmo monitorado" },
        { type: "red",   text: "⚠ 17 dos 26 jogadores atuam no futebol egípcio — gap enorme de nível competitivo" },
        { type: "amber", text: "⚠ Nenhuma vitória contra seleção top-20 nos últimos 12 meses (exceto Arábia Saudita)" },
      ],
      setpieces: {
        goalsPct: 35, concededPct: 22, cornersFor: 4.1,
        foulsSuffered: 10.2, penalties: 1,
        note: "Salah cobrador de falta de alto nível. 35% dos gols egípcios de situação parada — arma real",
      },
      style: {
        formation: "4-2-3-1",
        description: "Bloco baixo compacto, sacrifica a posse, aposta no contra-ataque via Salah e Marmoush. Defesa organizada e disciplinada.",
        possession: 36, passes: 290,
        pressing: 2, transition: 4, aerial: 3, creativity: 2, defensive: 5,
      },
      timing: {
        scored:   [2, 2, 3, 2, 3, 2, 1],
        conceded: [1, 1, 1, 1, 2, 1, 0],
        note: "Produção ofensiva baixa e concentrada em contra-ataques. Defesa sólida em todos os períodos",
      },
    },
    factors: [
      { label: "Poder ofensivo",          scoreA: 5, scoreB: 2, winner: "A" },
      { label: "Solidez defensiva",        scoreA: 3, scoreB: 4, winner: "B" },
      { label: "Qualidade individual",     scoreA: 5, scoreB: 3, winner: "A" },
      { label: "Profundidade do elenco",   scoreA: 5, scoreB: 2, winner: "A" },
      { label: "Exp. em Copas do Mundo",   scoreA: 4, scoreB: 2, winner: "A" },
      { label: "Forma pré-torneio",        scoreA: 5, scoreB: 3, winner: "A" },
      { label: "Ameaça de bola parada OF", scoreA: 3, scoreB: 4, winner: "B" },
      { label: "Vulnerab. defensiva BP",   scoreA: 3, scoreB: 4, winner: "B" },
      { label: "Capacidade de upset",      scoreA: 1, scoreB: 4, winner: "B" },
      { label: "Saúde do plantel",         scoreA: 3, scoreB: 3, winner: "tie" },
    ],
    probA: 58, probD: 26, probB: 16,
    prediction: "Bélgica 2-1 Egito",
    observation: "Bélgica vence com superioridade técnica, mas a defesa questionável (5 gols sofridos em 2 jogos vs Wales na qualificação) abre espaço para o Egito marcar. O gol egípcio — se vier — será de bola parada ou via Salah em transição quando a Bélgica sobe para o terceiro gol. Se o Egito marcar primeiro, o jogo muda emocionalmente — mas a Bélgica ainda tem qualidade individual para virar.",
    verdict: "Cruzando todos os vetores disponíveis, a Bélgica é a seleção com o ataque mais poderoso desta Copa: 2.45 xG por jogo (1º entre os 32 times), 37 gols nos últimos 10 jogos, e invicta há 13 partidas. O λ de Poisson resulta em λA≈1.75 e λB≈0.50 — o placar mais provável é 2-0 Bélgica com ~15%, seguido de 2-1 com ~13% e 1-0 com ~13%. Over 2.5 em ~52%. De Bruyne (8.0) operando como #10 livre em um 4-2-3-1 com Doku (7.5) pela direita cria uma sobrecarga de criatividade que nenhum bloco egípcio consegue cobrir durante 90 minutos — o intervalo de rating entre os meias dos dois times é de 1.0 ponto inteiro em média. O único ponto de vulnerabilidade estrutural da Bélgica é a zaga: Theate, Debast (duvidoso), e uma linha que cedeu 5 gols a Wales em qualificação — exatamente onde Salah pode atacar com espaço nas costas de Castagne. A questão do fitness de Salah precisa ser tratada com cuidado: entrou como substituto vs Brasil e hoje joga desde o início com 7 semanas de inatividade. Ele não está em 100% de ritmo e Marmoush precisará ser o motor do contra-ataque. No modelo ABDE, a Bélgica domina 6 dos 10 fatores, empata 1, e perde nos 3 critérios onde o Egito se apoia (defesa, bola parada ofensiva, capacidade de upset). O número que me incomoda nesta análise: o Egito venceu a Bélgica em 3 dos 4 confrontos históricos — mas nenhum deles envolveu uma Bélgica com este nível de pressing e produção ofensiva. Minha leitura cruzando todos os dados: Bélgica 2-1 com gol egípcio em situação parada ou transição no 2T quando a linha defensiva belga está mais esticada.",
    tags: [
      { text: "Bélgica favorita clara",     color: "blue"   },
      { text: "Over 2.5 gols (52%)",        color: "green"  },
      { text: "Salah — fitness duvidoso",   color: "amber"  },
      { text: "Lukaku — ritmo abaixo",      color: "amber"  },
      { text: "Defesa BEL — vulnerável",    color: "red"    },
      { text: "De Bruyne — motor do jogo",  color: "blue"   },
      { text: "EGY — 3V em 4 H2H",         color: "purple" },
      { text: "Debast — dúvida na zaga",    color: "red"    },
    ],
    group: "Grupo G", date: "15 Jun · 15h00 ET", venue: "Lumen Field · Seattle",
  },

  "bra-hai": {
    teamA: {
      name: "Brasil", flag: "🇧🇷", coach: "Carlo Ancelotti (desde mai/25)",
      avgAttack: 2.5, avgDef: 1.1,
      matches: [
        { opp: "x Chile",         score: "3-0", type: "W", date: "Set/25"  },
        { opp: "x Bolívia",       score: "0-1", type: "L", date: "Set/25"  },
        { opp: "x Coreia do Sul", score: "5-0", type: "W", date: "Out/25"  },
        { opp: "x Japão",         score: "2-3", type: "L", date: "Out/25"  },
        { opp: "x Senegal",       score: "2-0", type: "W", date: "Nov/25"  },
        { opp: "x Panamá",        score: "6-2", type: "W", date: "Mai/26"  },
        { opp: "x Egito",         score: "2-1", type: "W", date: "Jun/26"  },
        { opp: "x França",        score: "1-2", type: "L", date: "Mar/26"  },
        { opp: "x Croácia",       score: "3-1", type: "W", date: "Abr/26"  },
        { opp: "x Marrocos",      score: "1-1", type: "D", date: "Jun/26"  },
      ],
      players: [
        { pos: "GK", name: "Alisson Becker",       club: "Liverpool · 3ª Copa",                          rating: 7.5 },
        { pos: "RB", name: "Danilo",                club: "Flamengo — Wesley cortado por lesão",          rating: 6.9 },
        { pos: "CB", name: "Marquinhos (c)",        club: "PSG",                                          rating: 7.4 },
        { pos: "CB", name: "Gabriel Magalhães",     club: "Arsenal · cabeceador de elite",                rating: 7.5 },
        { pos: "LB", name: "Alex Sandro",           club: "Flamengo",                                     rating: 7.0 },
        { pos: "DM", name: "Casemiro",              club: "Manchester United",                             rating: 7.1 },
        { pos: "CM", name: "Bruno Guimarães",       club: "Newcastle · motor do meio",                    rating: 7.6 },
        { pos: "AM", name: "Lucas Paquetá",         club: "Flamengo",                                     rating: 7.2 },
        { pos: "RW", name: "⭐ Raphinha",           club: "Barcelona · 5G nas eliminatórias",             rating: 7.8 },
        { pos: "LW", name: "⭐ Vinicius Jr.",       club: "Real Madrid · 1G vs Marrocos",                 rating: 8.0 },
        { pos: "ST", name: "Matheus Cunha",         club: "Wolves · substitui Igor Thiago no 11 titular", rating: 7.0 },
      ],
      alerts: [
        { type: "red",   text: "⚠ Neymar — lesão grau 2 na panturrilha; não jogou vs Marrocos; possível estreia aqui mas sem garantia" },
        { type: "red",   text: "⚠ Militão, Rodrygo e Estêvão — cortados antes da Copa por lesão" },
        { type: "amber", text: "⚠ Brasil empatou 1x1 vs Marrocos — pressão máxima, vitória é obrigatória" },
        { type: "amber", text: "⚠ Igor Thiago abaixo do esperado vs Marrocos — Cunha assume a titularidade" },
      ],
      setpieces: {
        goalsPct: 31, concededPct: 24, cornersFor: 6.2,
        foulsSuffered: 11.8, penalties: 2,
        note: "Gabriel Magalhães — cabeceador de elite em escanteios. Raphinha e Paquetá cobradores precisos",
      },
      style: {
        formation: "4-3-3 / 4-2-3-1",
        description: "Jogo pelos flancos com Vini e Raphinha. Ancelotti libera criatividade individual. Transições rápidas. Vs Haiti vai dominar a posse e usar largura para abrir espaços.",
        possession: 72, passes: 520,
        pressing: 4, transition: 5, aerial: 3, creativity: 5, defensive: 3,
      },
      timing: {
        scored:   [3, 4, 3, 4, 5, 5, 1],
        conceded: [1, 2, 2, 2, 1, 3, 0],
        note: "Produtivo em todos os períodos — cresce no 2T. Sem período de apagão",
      },
    },
    teamB: {
      name: "Haiti", flag: "🇭🇹", coach: "Sébastien Migné (desde jun/24)",
      avgAttack: 1.2, avgDef: 1.0,
      matches: [
        { opp: "x Costa Rica",   score: "3-3", type: "D", date: "Set/25"  },
        { opp: "x Nicaragua",    score: "3-0", type: "W", date: "Out/25"  },
        { opp: "x Honduras",     score: "0-3", type: "L", date: "Out/25"  },
        { opp: "x Costa Rica",   score: "1-0", type: "W", date: "Nov/25"  },
        { opp: "x Nicaragua",    score: "2-0", type: "W", date: "Nov/25"  },
        { opp: "x Tunísia",      score: "0-1", type: "L", date: "Mar/26"  },
        { opp: "x Islândia",     score: "1-1", type: "D", date: "Mar/26"  },
        { opp: "x NZ (amistoso)",score: "4-1", type: "W", date: "Mar/26"  },
        { opp: "x Escócia",      score: "0-1", type: "L", date: "Jun/26"  },
        { opp: "x Costa Rica",   score: "3-3", type: "D", date: "Set/25"  },
      ],
      players: [
        { pos: "GK", name: "Johny Placide (c)",      club: "SC Bastia · capitão · mais experiente do grupo", rating: 6.8 },
        { pos: "RB", name: "Jean-Kévin Duverne",     club: "KAA Gent (BEL)",                                 rating: 6.6 },
        { pos: "CB", name: "Ricardo Adé",            club: "LDU Quito · 36 anos · liderança defensiva",      rating: 6.8 },
        { pos: "CB", name: "Carlens Arcus",          club: "Angers (FRA)",                                   rating: 6.7 },
        { pos: "LB", name: "Hannes Delcroix",        club: "Lugano (SUI)",                                   rating: 6.6 },
        { pos: "MF", name: "⭐ Jean-Ricner Bellegarde", club: "Wolverhampton · Premier League · qualidade real", rating: 7.3 },
        { pos: "MF", name: "Carl-Fred Sainthe",      club: "El Paso Locomotive (USA)",                       rating: 6.5 },
        { pos: "MF", name: "Jean-Jacques Danley",    club: "Philadelphia Union",                              rating: 6.5 },
        { pos: "MF", name: "Yassin Fortune",         club: "FC Vizela (POR)",                                rating: 6.6 },
        { pos: "ST", name: "⭐ Wilson Isidor",       club: "Sunderland · 5G na temporada · ex-França",       rating: 7.1 },
        { pos: "ST", name: "⭐ Duckens Nazon",       club: "Esteghlal · 44G/76caps · artilheiro histórico",  rating: 7.0 },
      ],
      alerts: [
        { type: "green", text: "✔ Competiu de igual vs Escócia — organização tática surpreendeu" },
        { type: "amber", text: "⚠ Frantzdy Pierrot — lesionado, fora do jogo" },
        { type: "amber", text: "⚠ Migné nunca visitou o Haiti — treinamentos sempre em campo neutro" },
        { type: "red",   text: "⚠ Nenhuma vitória na história da Copa do Mundo (3D em 1974)" },
        { type: "red",   text: "⚠ Eliminado praticamente — precisa que Brasil e Marrocos percam para ter chance" },
      ],
      setpieces: {
        goalsPct: 40, concededPct: 30, cornersFor: 3.8,
        foulsSuffered: 10.1, penalties: 0,
        note: "40% dos gols de bola parada — Bellegarde cobrador de nível. Vulnerável aerialmente em escanteios contra",
      },
      style: {
        formation: "4-4-2 / 4-5-1",
        description: "Dois blocos compactos de quatro. Sacrifica totalmente a posse, aposta na organização coletiva e contra-ataque via Isidor e Nazon. Vs Escócia aguentou 90 min — mas Brasil é outro patamar.",
        possession: 28, passes: 230,
        pressing: 1, transition: 4, aerial: 3, creativity: 1, defensive: 5,
      },
      timing: {
        scored:   [1, 2, 2, 2, 2, 2, 1],
        conceded: [2, 2, 1, 2, 2, 3, 0],
        note: "Cede mais no 2T — especialmente após os 75 min quando o bloco se abre por cansaço",
      },
    },
    factors: [
      { label: "Qualidade ofensiva",        scoreA: 5, scoreB: 1, winner: "A" },
      { label: "Solidez defensiva",          scoreA: 3, scoreB: 4, winner: "B" },
      { label: "Qualidade individual",       scoreA: 5, scoreB: 1, winner: "A" },
      { label: "Profundidade do elenco",     scoreA: 5, scoreB: 1, winner: "A" },
      { label: "Exp. em Copas do Mundo",     scoreA: 5, scoreB: 1, winner: "A" },
      { label: "Motivação / pressão",        scoreA: 5, scoreB: 2, winner: "A" },
      { label: "Organização defensiva",      scoreA: 3, scoreB: 4, winner: "B" },
      { label: "Capacidade de upset",        scoreA: 1, scoreB: 3, winner: "B" },
      { label: "Ritmo competitivo",          scoreA: 4, scoreB: 3, winner: "A" },
      { label: "Saúde do plantel",           scoreA: 3, scoreB: 4, winner: "B" },
    ],
    probA: 82, probD: 12, probB: 6,
    prediction: "Brasil 3-0 Haiti",
    observation: "Brasil entra sob pressão existencial após o empate com Marrocos — paradoxalmente isso é vantagem, pois Ancelotti não vai poupar ninguém e a equipe joga com urgência real. Vini e Raphinha vão ser libertados pelos flancos desde o 1T. Haiti vai resistir por 30–40 min com o bloco, mas quando o primeiro gol sair o jogo abre. O único perigo real é Bellegarde em bola parada no 1T com placar em 0-0 — se o Brasil fizer falta imprudente na entrada da área.",
    verdict: "Este jogo tem uma dimensão que vai além dos dados puros: o Brasil entra pressionado após o empate com o Marrocos e não pode se dar ao luxo de tropeçar. O λ de Poisson sobe para ≈2.80 nesse contexto de necessidade, contra ≈0.35 do Haiti — Over 2.5 em 72%, o número mais alto de todas as análises desta Copa. O placar mais provável é 3-0 com ~18%, seguido de 2-0 com ~17% e 4-0 com ~11%. A diferença de qualidade individual é astronômica: Vinicius Jr. (8.0) contra Duverne (6.6) na lateral — um mismatch de 1.4 pontos de rating que nenhum sistema tático consegue cobrir por 90 minutos. O Haiti mostrou organização real vs Escócia, mas existem dois níveis de dificuldade entre a Escócia e este Brasil com Vini livre pela esquerda. O Haiti vai manter o bloco por 30-40 minutos, criando ansiedade no Brasil, mas quando Vini ou Raphinha resolverem no um-contra-um — e vão resolver — os espaços para o segundo e terceiro gols aparecem naturalmente. Os 40% dos gols haitianos de bola parada são o único número que justifica atenção: Bellegarde cobra bem e pode surpreender se o Brasil fizer falta desnecessária. A possível estreia de Neymar pode mudar o timing tático — se entrar, a imprevisibilidade aumenta para ambos os lados nos primeiros 10 minutos. Mas a diferença é grande demais. Minha leitura: Brasil 3-0, com os gols distribuídos — um no 1T (abertura do bloco), dois no 2T (espaços maiores). Under 2.5 não tem nenhuma base nos dados aqui.",
    tags: [
      { text: "Brasil favorito absoluto (82%)", color: "blue"   },
      { text: "Over 2.5 fortíssimo (72%)",       color: "green"  },
      { text: "Vini Jr. — destruidor pelo flanco", color: "blue" },
      { text: "Neymar — possível estreia",         color: "amber" },
      { text: "Brasil precisa vencer",             color: "amber" },
      { text: "Haiti 0V na história da Copa",      color: "red"   },
      { text: "H2H: BRA 3V 0D (7-1 em 2016)",    color: "blue"  },
      { text: "Bellegarde — único perigo HAI",     color: "purple"},
    ],
    group: "Grupo C", date: "19 Jun · 21h30 BRT", venue: "Lincoln Financial Field · Filadélfia",
    note: "⚠ Contexto pós-rodada 1: Brasil 1x1 Marrocos · Haiti 0x1 Escócia · Escócia lidera com 3pts",
  },
  
};

export const MATCH_OPTIONS = [
  { key: "bra-mar",  label: "🇧🇷 Brasil vs 🇲🇦 Marrocos (pré-jogo)" },
  { key: "iran-nz",  label: "🇮🇷 Irã vs 🇳🇿 Nova Zelândia" },
  { key: "fra-sen",  label: "🇫🇷 França vs 🇸🇳 Senegal" },
  { key: "bel-egy", label: "🇧🇪 Bélgica vs 🇪🇬 Egito" },
  { key: "sau-uru",  label: "🇸🇦 Arábia Saudita vs 🇺🇾 Uruguai" },
  { key: "bra-hai", label: "🇧🇷 Brasil vs 🇭🇹 Haiti" },
];